<?php

$latestFlag = file_get_contents('latest-link.txt');
$leaks = scrapeWebsite();
$currentFlag = file_get_contents('latest-link.txt');
$today = date('d M Y');

$botToken = 'your-bot-token';
$channel = 'your-channel-id';

if ($latestFlag === $currentFlag) {
    exit;
}

$message = ":bangbang: Yeni veri ihlali var ($today)\n";
foreach ($leaks as $leak) {

    if ($leak['link'] === $latestFlag) {
        break;
    }

    $title = urlencode($leak['title']);
    $message .= "• <{$leak['link']}|$title> ({$leak['date']})\n";
}
chatPostMessage($channel, $message, $botToken);

function scrapeWebsite()
{
    $url = 'https://www.kvkk.gov.tr/veri-ihlali-bildirimi';

    $curl = curl_init($url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($curl, CURLOPT_HTTPHEADER, array(
        'User-Agent: Mozilla/5.0 (iPhone14,6; U; CPU iPhone OS 15_4 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/19E241 Safari/602.1'
    ));

    $response = curl_exec($curl);

    if ($response === false) {
        die('Error in cURL request: ' . curl_error($curl));
    }

    curl_close($curl);

    $dom = new DOMDocument();
    @$dom->loadHTML($response); // The @ is used to suppress warnings generated by invalid HTML structures

    $xpath = new DOMXPath($dom);

    $items = $xpath->query("//div[contains(@class,'news__box')]");

    $result = [];
    $i = 0;

    foreach ($items as $item) {

        $titleNode = $xpath->query(
            ".//div[@class='news__box-meta']/a/@title",
            $item
        );
        $title = $titleNode->item(0)->nodeValue;

        $linkNode = $xpath->query(
            ".//div[@class='news__box-meta']/a/@href",
            $item
        );
        $link = $linkNode->item(0)->nodeValue;

        $dateNode = $xpath->query(".//p[contains(@class,'date')]", $item)->item(0);
        $date = trim($dateNode->textContent);

        if (!$title || !$link) {
            continue; // 🚫 skip empty / invalid blocks
        }

        if ($i === 0) {
            file_put_contents('latest-link.txt', $link);
        }

        $i++;

        $result[] = [
            'title' => $title,
            'link'  => $link,
            'date'  => $date,
        ];
    }

    return $result;
}

function chatPostMessage($channel, $message, $botToken)
{
    $url = 'https://slack.com/api/chat.postMessage';
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_TIMEOUT, 10);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "channel=$channel&text=$message");

    $headers = [
        "Authorization: Bearer $botToken",
        'Content-Type: application/x-www-form-urlencoded'
    ];

    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    $output = curl_exec($ch);

    if ($output === false) {
        echo 'Curl error: ' . curl_error($ch);
        exit;
    }

    curl_close($ch);
}